### PR TITLE
some improvements in style and in codes

### PR DESCRIPTION
**Pull request by ahmadnourallah**
in this comment I will  explaining the changes i have made to the project
i have added modifications to the appearance of the blog, such as changing the shape of buttons and writing fields and adding effects to add more aesthetics
i added a simple control panel to modify the configuration file
i added simple error message to appear when login failed 
and many another improvements

### CODE REVIEW

**Comment by mhsabbagh** [comment]
Please, next time you submit a pull request, open a new ticket in the issues page for such huge update first. This is essential in any open source project.

You are submitting 11 commits together here. Some of them could be accepted and some of them not. However, in this way, I am forced to reject all of it since you are bundling them together. 

1- I don't see the point in creating a control panel. Modifying the values of the configuration file is a lot more time saver than creating a control panel to modify only 10 lines of configurations. Also remember that this project is not a replacement for common CMSs. In other words, if a user is too newbie to be able to modify it, then he wouldn't be able to deploy it in the first place.

2- Your new login method which depends on hashing doesn't work. Login always shows an error message here. Unless you can store the password in the database as an encrypted string, then you should keep it as a plain text in the configuration file. Because the user won't hash the password by himself.

**Comment by ahmadnourallah** [comment]
First, thank you for your comment
1 - I think that your project aimed at the normal user and the existence of a control panel is great to provide the user, what prevents the lack of it?
2 - If an attacker has access to the configuration file it will be easy to get the password simply and this is not convenient in terms of security for this I have encrypted the password
Of course, the user will not encrypt the password and compare it with the password in the configuration file when the user logs on. The site encrypts the entered password and compares it with that in the configuration file.
Why not work Have you tried it?

**Comment by mhsabbagh** [comment]
1- No. A "normal user" wouldn't necessarily know how to deploy a Python script via uwsgi or the other tools available. It's not the same as something like WordPress. (Which, by the way, stores the MYSQL configuration info in wp-config.php file, just as we do). If he can't edit the file, he probably shouldn't use the script.

2- As I said. This is the same thing which we have in the major CMSs. Joomla, Drupal & WordPress all store the database username and password in a plain text file (config.php or something). If the server is compromised, then the whole website is gone. And the whole database is gone. No need to worry about what he can publish or delete from our simple login page.

What I see from the pull request you submitted is that you entered a hash instead of the password in the configuration file. Not the plain password as you described here.

**Comment by ahmadnourallah** [comment]
1 - It's not about the ability of user to modify the configuration file ... Imagine that every time you want to modify the description of the site example from the configuration file will you connect to your remote server and open the file in one of the editors Why I forced the user to do this ??
In contrast, I can write a simple control panel that enables the user to edit the configuration file from his browser directly (if he has the permissions) I don't see a reason to make you oppose this !!
2- A configuration file in Wordpress contains a database password and not user passwords so it is quite different so if the site drops you will not drop users too !! And again I don't see a reason to make you oppose this too !! Because it will not cause harm to the user or project

**Comment by mhsabbagh** [comment]
Which is why I told you that you should have discussed that before you submit 11 commits together. This is a minimalist script. Not a real alternative to anything you see online. Writing and modifying 250 lines of code to allow editing a file consisting of 10 lines is a waste of effort and time and contradicts with everything this script is about.

Feel free to submit your other "style related" commits alone in separate pull requests for each.

**Pull request closed without merging**
